### PR TITLE
seeders for jobs, programs and cohorts

### PR DESCRIPTION
**Pull request by berniceu**
This PR runs seeders for jobs, programs and cohorts

run this command to run the seeders
```
npm run seed
```
the database should then be populated

Screenshot 2024-09-15 231529

### CODE REVIEW

**Comment by berniceu** [comment]
This PR runs seeders for jobs, programs and cohorts

run this command to run the seeders
```
npm run seed
```
the database should then be populated

Screenshot 2024-09-15 231529

**Review by MUNYESHURImanzi — APPROVED** [review]
well done

**Review by bahati10 — APPROVED** [review]
Good job for adding seeders.
very much needed indeed.

**Review by Aime-Patrick — APPROVED** [review]

**Review by ncutixavier — COMMENTED** [review]
Remove all logs

**Review by SHYAKA-Aime — APPROVED** [review]

**Pull request merged**
