### PR TITLE
Ch trainee applicant collections

### PR DESCRIPTION
**Pull request by Hodal66**
### What does this PR do?

• add trainee applicant collection entree

**How should this be manually tested?**

• Run `git clone https://github.com/atlp-rwanda/atlp-devpulse-bn` to clone the project

• Run `cd atlp-devpulse-bn`to go to the root project

• Run `git fetch` to fetch all branches to your local machine

• Run `git checkout ch-trainee-applicant-collections`

• Run `npm i` or `npm install` to install all used dependencies

• Run `npm run dev` to start the server

**What to expect?**
Any one who will need to use trainee credentials will import trainee from  model and able to use it.

**Check Other preference** on [Trello](https://trello.com/c/IqZaC2YB/26-trainee-applicant-collection)

### CODE REVIEW

**Review by PrinceNiyonshuti — CHANGES_REQUESTED** [review]
Do we only have those fields for the Trainee?
also can we populate all the fields

**Review by Gedeonir — APPROVED** [review]

**Review by Gedeonir — APPROVED** [review]
looks good to me

**Review by Gedeonir — COMMENTED** [review]
but try to squash commits

**Comment by Hodal66** [comment]
We have many collection but we choose the basic one because others belong to another tasks

**Review by istafrica-dennw — APPROVED** [review]

**Review by PrinceNiyonshuti — APPROVED** [review]
LGTM

**Pull request merged**
